<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2018 Power Kernel
 */


namespace powerkernel\yiicore\controllers;

use powerkernel\yiicore\forms\AuthGetTokenForm;
use powerkernel\yiicore\forms\AuthRequestForm;
use powerkernel\yiicore\forms\AuthVerifyForm;
use powerkernel\yiicore\models\Auth;


/**
 * Class AuthController
 */
class AuthController extends \yii\rest\Controller
{

    /**
     * @inheritdoc
     * @var array
     */
    public $serializer = [
        '__class' => \yii\rest\Serializer::class,
        'collectionEnvelope' => 'items',
    ];

    /**
     * @inheritdoc
     * @return array
     */
    protected function verbs()
    {
        return [
            'verify' => ['POST'],
            'request' => ['POST'],
            'get-access-token' => ['POST'],
        ];
    }

    /**
     * @param $action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        if (\Yii::$app->request->isPost || \Yii::$app->request->isPatch) {
            \Yii::$app->request->setHeader('Content-Type', 'application/json');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * request for authentication
     * @return array
     * @throws \yii\base\InvalidConfigException
     * @throws \yii\web\UnsupportedMediaTypeHttpException
     */
    public function actionRequest()
    {
        $form = new AuthRequestForm();
        $form->load(\Yii::$app->getRequest()->getParsedBody(), '');
        if ($form->validate()) {
            $auth = new Auth();
            $auth->identifier = $form->identifier;
            if ($auth->save()) {
                return [
                    'success' => true,
                    'data' => [
                        'id' => (string)$auth->getId(),
                        'identifier' => $auth->identifier,
                    ]
                ];
            }
        }
        return [
            'success' => false,
            'data' => [
                'errors' => $form->errors
            ]
        ];
    }

    /**
     * @return array
     * @throws \yii\base\InvalidConfigException
     * @throws \yii\web\UnsupportedMediaTypeHttpException
     */
    public function actionVerify()
    {
        $form = new AuthVerifyForm();
        $form->load(\Yii::$app->getRequest()->getParsedBody(), '');
        if ($form->validate()) {
            return [
                'success' => true,
                'data' => $form->data
            ];
        }

        return [
            'success' => false,
            'data' => [
                'errors' => $form->errors
            ]
        ];

    }

    /**
     * Get access token
     * @return array
     * @throws \yii\base\InvalidConfigException
     * @throws \yii\web\UnsupportedMediaTypeHttpException
     */
    public function actionGetAccessToken(){
        $form = new AuthGetTokenForm();
        $form->load(\Yii::$app->getRequest()->getParsedBody(), '');
        if ($form->validate()) {
            return [
                'success' => true,
                'data' => $form->data
            ];
        }

        return [
            'success' => false,
            'data' => [
                'errors' => $form->errors
            ]
        ];
    }
}
