<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2018 Power Kernel
 */

namespace powerkernel\yiicore\v1;

/**
 * Class Module
 * Core API Module
 */
class Module extends \yii\base\Module
{

    public $controllerNamespace = 'powerkernel\yiicore\v1\controllers';
    public $defaultRoute = 'default';

    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}