<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2018 Power Kernel
 */

namespace powerkernel\yiicore\models;

use powerkernel\yiicommon\behaviors\UTCDateTimeBehavior;


/**
 * Class Auth
 * @package powerkernel\yiicore\models
 *
 * @property mixed $_id
 * @property string $identifier
 * @property string $code
 * @property string $auth_key
 * @property string $ip
 * @property integer $attempts
 * @property string $status
 * @property \MongoDB\BSON\UTCDateTime $created_at
 * @property \MongoDB\BSON\UTCDateTime $updated_at
 */
class Auth extends \yii\mongodb\ActiveRecord
{
    const STATUS_NEW = 'STATUS_NEW';
    const STATUS_VERIFIED = 'STATUS_VERIFIED';
    const STATUS_UNVERIFIED = 'STATUS_UNVERIFIED';
    const STATUS_USED = 'STATUS_USED';

    /**
     * @inheritdoc
     */
    public static function collectionName()
    {
        return 'core_auth';
    }

    /**
     * @return array
     */
    public function attributes()
    {
        return [
            '_id',
            'identifier',
            'code',
            'auth_key',
            'ip',
            'attempts',
            'status',
            'created_at',
            'updated_at',
        ];
    }

    /**
     * get id
     * @return \MongoDB\BSON\ObjectID|string
     */
    public function getId()
    {
        return $this->_id;
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            UTCDateTimeBehavior::class,
        ];
    }

    /**
     * @return int timestamp
     */
    public function getUpdatedAt()
    {
        return $this->updated_at->toDateTime()->format('U');
    }

    /**
     * @return int timestamp
     */
    public function getCreatedAt()
    {
        return $this->created_at->toDateTime()->format('U');
    }


    /**
     * get status list
     * @param null $e
     * @return array
     */
    public static function getStatusOption($e = null)
    {
        $option = [
            self::STATUS_NEW => \Yii::t('core', 'New'),
            self::STATUS_USED => \Yii::t('core', 'Used'),
        ];
        if (is_array($e))
            foreach ($e as $i)
                unset($option[$i]);
        return $option;
    }

    /**
     * get status text
     * @return string
     */
    public function getStatusText()
    {
        $status = $this->status;
        $list = self::getStatusOption();
        if (!empty($status) && in_array($status, array_keys($list))) {
            return $list[$status];
        }
        return \Yii::t('core', 'Unknown');
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        $default = [
            [['identifier'], 'required'],
            [
                'identifier',
                'match',
                'pattern' => '/^(\+[1-9][0-9]{9,14})|([a-zA-Z0-9!#$%&\'*+\\/=?^_`{|}~-]+(?:\.[a-zA-Z0-9!#$%&\'*+\\/=?^_`{|}~-]+)*@(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?)$/',
                'message' => \Yii::t('core', 'Identifier must be an email or a phone number.')
            ],
            [['identifier', 'code'], 'trim'],
            ['code', 'string', 'length' => 6],
            [['code'], 'match', 'pattern' => '/^[0-9]{6}$/'],

            ['attempts', 'default', 'value' => 0],
            ['status', 'default', 'value' => Auth::STATUS_NEW],
            ['auth_key', 'string', 'max' => 32],
            ['status', 'string', 'max' => 20],
            [['created_at', 'updated_at'], 'yii\mongodb\validators\MongoDateValidator'],
        ];

        return $default;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'identifier' => \Yii::t('core', 'Identifier'),
            'code' => \Yii::t('core', 'Verification code'),
            'auth_key' => \Yii::t('core', 'Auth key'),
            'status' => \Yii::t('core', 'Status'),
            'created_at' => \Yii::t('core', 'Created At'),
            'updated_at' => \Yii::t('core', 'Updated At'),
        ];
    }

    /**
     * @inheritdoc
     * @param bool $insert
     * @return bool
     * @throws \yii\base\Exception
     */
    public function beforeSave($insert)
    {
        if ($insert) {
            $this->status = self::STATUS_NEW;
            $this->ip = \Yii::$app->request->userIP;
            $this->generateAuthKey();
            $this->code = (string)rand(100000, 999999);
        } else {
            if ($this->attempts >= 3) {
                $this->status = self::STATUS_UNVERIFIED;
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     * @param bool $insert
     * @param array $changedAttributes
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        /* send code */
        if($insert){
            if ($this->getType() == 'phone') {
                $this->sendSMS();
            }
            if ($this->getType() == 'email') {
                $this->sendEmail();
            }
        }

    }

    /**
     * Generates authentication key
     * @throws \yii\base\Exception
     */
    public function generateAuthKey()
    {
        $this->auth_key = \Yii::$app->security->generateRandomString();
    }


    /**
     * get identifier type
     * @return bool|string
     */
    public function getType()
    {
        $patterns = [
            'phone' => '/^\+[1-9][0-9]{9,14}$/',
            'email' => '/^[a-zA-Z0-9!#$%&\'*+\\/=?^_`{|}~-]+(?:\.[a-zA-Z0-9!#$%&\'*+\\/=?^_`{|}~-]+)*@(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$/'
        ];
        foreach ($patterns as $type => $pattern) {
            if (preg_match($pattern, $this->identifier)) {
                return $type;
            }
        }
        return false;
    }

    /**
     * send SMS code
     * @return bool
     */
    protected function sendSMS()
    {
        return \Yii::$app->sns->client->publish([
            'Message' => \Yii::t('core', '{APP}: Your verification code is {CODE}', ['CODE' => $this->code, 'APP' => \Yii::$app->name]),
            'PhoneNumber' => $this->identifier
        ]);
    }

    /**
     * send email code
     * @return bool
     */
    protected function sendEmail()
    {
        $subject = \Yii::t('core', 'Verification code for {APP}', ['APP' => \Yii::$app->name]);
        return \Yii::$app->mailer
            ->compose(
                [
                    'html' => '@vendor/powerkernel/yii-core-api/src/mail/auth-request-html',
                    'text' => '@vendor/powerkernel/yii-core-api/src/mail/auth-request-text'
                ],
                [
                    'model' => $this,
                ]
            )
            ->setFrom(\Yii::$app->params['mailer']['from'])
            ->setTo($this->identifier)
            ->setSubject($subject)
            ->send();
    }

    /**
     * get access token
     * @return bool|string
     */
    public function getAccessToken()
    {
        $type = $this->getType();
        if($type=='email'){
            $user = User::find()
                ->where(['email' => $this->identifier])
                ->one();
            if (!$user) {
                $user = new User();
                $user->name = $this->identifier;
                $user->email = $this->identifier;
                if (!$user->save()) {
                    return false;
                }
            }
            return $user->access_token;
        }
        return false;
    }
}