<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2018 Power Kernel
 */

namespace powerkernel\yiicore;

/**
 * Class Module
 * Core API Module
 */
class Module extends \yii\base\Module
{

    public $controllerNamespace = 'powerkernel\yiicore\controllers';
    public $defaultRoute = 'user';

    /**
     * @inheritdoc
     */
    public function init()
    {
        //$this->configUrlManager();
        parent::init(); // TODO: Change the autogenerated stub



    }

    /**
     * configUrlManager
     */
    protected function configUrlManager()
    {
        $urlManagerFile = __DIR__ . '/urlManager.php';
        if (file_exists($urlManagerFile)) {
            $urlManagerConfig = require($urlManagerFile);
            if (!empty($urlManagerConfig['rules'])) {
                $rules = $urlManagerConfig['rules'];
                \Yii::$container->set('yii\web\UrlManager', [
                    'rules' => $rules
                ]);
            }
        }
    }
}